# Gatekeeper Base Installation (for App of Apps)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: "3.17.1"
    helm:
      values: |
        replicas: 2
        exemptNamespaces:
          - kube-system
          - gatekeeper-system
          - argocd
          - istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
