apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: secure-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: hashicorp/http-echo:0.2.3
          args: ["-text", "hello from the mesh"]
          ports:
            - containerPort: 5678
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
