apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: secure-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsNonRoot:  true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: helloworld
          image: docker.io/istio/examples-helloworld-v1  ### hashicorp/http-echo:0.2.3
          args: ["-text", "hello from the mesh"]
          ports:
            - containerPort: 5678
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault