apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-extension
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/secure-service-mesh.git
    path: apps/opa-extension
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
