apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: opa-authz
  namespace: secure-apps
spec:
  action: CUSTOM
  provider:
    name: opa-authz
  rules:
    - to:
        - operation:
            paths: ["*"]
