apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.50.2-envoy
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
            - "--set=decision_logs.console=true"
            - "--set=default_decision=envoy/authz/allow"
            - "/policy/policy.rego"
          volumeMounts:
            - mountPath: /policy
              name: policy
      volumes:
        - name: policy
          configMap:
            name: opa-policy
