apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.26.2
    helm:
      values: |-
        cni:
          # Critical: Set chained to false
          chained: false
          # Proper paths for most Kubernetes distributions
          cniBinDir: /opt/cni/bin
          cniConfDir: /etc/cni/net.d
          # Exclude system namespaces
          excludeNamespaces:
          - istio-system
          - kube-system
          - argocd
          # Enable repair functionality
          repair:
            enabled: true
            deletePods: true
            repairPods: true
            initContainerName: "istio-validation"
          # Important: Set log level for debugging
          logLevel: info
        # Configure for restricted environments
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
          seccompProfile:
            type: RuntimeDefault
        # Resource constraints
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true