apiVersion: constraints.gatekeeper.sh/v1beta1
kind: UniqueVirtualServiceHost  # Must match the Kind from ConstraintTemplate
metadata:
  name: unique-vs-hosts
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["networking.istio.io"]
        kinds: ["VirtualService"]
  parameters:
    exemptNamespaces:
      - istio-system
      - istio-operator
      - kube-system
      - gatekeeper-system