apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-extension
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:shackdan/secure-cluster.git
    path: manifests/opa-extension
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
