apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.26.2"
    helm:
      values: |
        # Global CNI configuration - CRITICAL for disabling init containers
        global:
          istio_cni:
            enabled: true
            chained: true
          # Configure CA properly for local/self-signed CA
          meshID: mesh1
          network: network1
          # Explicitly disable external CA
          caAddress: ""
          # Configure to use local CA
          remotePilotAddress: ""
          # Add explicit trust domain
          trustDomain: "cluster.local"
          # Add explicit CA settings
          jwtPolicy: "third-party-jwt"
        
        # Mesh configuration to use CNI
        meshConfig:
          defaultConfig:
            proxyMetadata:
              ISTIO_META_CNI_ENABLED: "true"
        
        pilot:
          env:
            EXTERNAL_ISTIOD: false
            # Explicitly set CA mode to local
            PILOT_ENABLE_WORKLOAD_TRUST_BUNDLES: true
            VALIDATION_WEBHOOK_CONFIG_NAME: "istio-validator-istio-system"
            # CNI-related environment variables
            ISTIO_CNI_ENABLED: "true"
            # Add explicit CA configuration - only add what's not already defined
            CA_ADDR: "istiod.istio-system.svc:15012"
          
          service:
            ports:
              - port: 15010
                name: grpc-xds
                protocol: TCP
              - port: 15012
                name: tls-istiod
                protocol: TCP
              - port: 15014
                name: http-monitoring
                protocol: TCP
          
          # Updated readiness probe configuration
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          
          # Add liveness probe
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
        
        # Configure istiod to use local CA
        istiodRemote:
          enabled: false
        
        # Explicitly configure local CA settings
        ca:
          # Use self-signed root CA
          address: ""
          # Configure CA signing settings
          env:
            # Ensure local CA is used
            EXTERNAL_CA: false
        
        # Sidecar injector configuration
        sidecarInjectorWebhook:
          enableNamespacesByDefault: false
          objectSelector:
            enabled: true
          namespaceSelector:
            matchExpressions:
              - key: istio-injection
                operator: In
                values:
                  - enabled
          templates:
            sidecar: |
              spec:
                containers:
                  - name: istio-proxy
                    image: docker.io/istio/proxyv2:1.26.2
                    args:
                      - proxy
                      - sidecar
                      - --domain
                      - $(POD_NAMESPACE).svc.cluster.local
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    volumeMounts:
                      - name: istio-envoy
                        mountPath: /etc/istio/proxy
                      - name: istio-root-cert
                        mountPath: /var/run/secrets/istio
                        readOnly: true
                volumes:
                  - name: istio-envoy
                    emptyDir: {}
                  - name: istio-root-cert
                    configMap:
                      name: istio-ca-root-cert
        
        # Configure autoscaling to reduce HPA drift
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 5
        
        # Configure resources to reduce deployment drift
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 500m
            memory: 2048Mi
      patches:
        - target:
            kind: MutatingWebhookConfiguration
            name: istio-sidecar-injector
          patch: |-
            - op: add
              path: /webhooks/0/namespaceSelector
              value:
                matchExpressions:
                  - key: istio-injection
                    operator: In
                    values:
                      - enabled
        # Add PeerAuthentication patch
        - target:
            group: security.istio.io
            version: v1beta1
            kind: PeerAuthentication
            name: default
            namespace: istio-system
          patch: |-
            - op: add
              path: /spec
              value:
                mtls:
                  mode: PERMISSIVE