apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IstioMTLSRequired
metadata:
  name: require-istio-mtls
spec:
  match:
    kinds:
      - apiGroups: ["networking.istio.io"]
        kinds: ["DestinationRule"]
