defaultRevision: default
meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
    proxy:
      privileged: false
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo sidecar started"]
components:
  cni:
    enabled: true
values:
  global:
    proxy:
      autoInject: enabled
      privileged: false
    istioNamespace: istio-system
  pilot:
    autoscaleEnabled: true
