apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8spspprivilegedcontainer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  crd:
    spec:
      names:
        kind: K8sPSPPrivilegedContainer
      validation:
        openAPIV3Schema:
          type: object
          properties:
            exemptNamespaces:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspprivilegedcontainer

        ns_in_exempt {
          some i
          input.parameters.exemptNamespaces[i] == input.review.object.metadata.namespace
        }
        
        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          not ns_in_exempt
        
          container := input.review.object.spec.containers[_]
          container.securityContext.privileged == true
        
          msg := sprintf("Privileged container not allowed in Pod %v", [input.review.object.metadata.name])
        }



