apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: istiomtlsrequired
spec:
  crd:
    spec:
      names:
        kind: IstioMTLSRequired
        listKind: IstioMTLSRequiredList
      validation:
        openAPIV3Schema:
          type: object
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package istio.security.mtls

        violation[{"msg": msg}] {
          input.review.kind.kind == "DestinationRule"
          input.review.kind.group == "networking.istio.io"

          not input.review.object.spec.trafficPolicy.tls.mode == "ISTIO_MUTUAL"

          msg := sprintf("DestinationRule %v must enforce ISTIO_MUTUAL", [input.review.object.metadata.name])
        }
