apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8spspseccomp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  crd:
    spec:
      names:
        kind: K8sPSPSeccomp
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedProfiles:
              type: array
              items:
                type: string
            exemptNamespaces:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspseccomp

        ns_is_exempt {
          input.review.object.metadata.namespace == input.parameters.exemptNamespaces[_]
        }
        
        profile_allowed(profile) {
          profile == input.parameters.allowedProfiles[_]
        }
        
        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          not ns_is_exempt
        
          profile := input.review.object.spec.securityContext.seccompProfile.type
          not profile_allowed(profile)
        
          msg := sprintf("Pod %v must use an allowed seccompProfile. Found: %v", [input.review.object.metadata.name, profile])
        }

