apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: uniquevshost
spec:
  crd:
    spec:
      names:
        kind: UniqueVirtualServiceHost
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package istio.security.vshost

        violation[{"msg": msg}] {
          input.review.kind.kind == "VirtualService"
          host := input.review.object.spec.hosts[_]
          other := data.inventory.namespace["networking.istio.io/VirtualService"]
          some vs in other
          vs.spec.hosts[_] == host
          vs.metadata.name != input.review.object.metadata.name
          msg := sprintf("VirtualService %v reuses host %v already claimed by %v", [input.review.object.metadata.name, host, vs.metadata.name])
        }
