apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-istio-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/secure-service-mesh.git
    path: apps/gatekeeper
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
