apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8srequiredprobes
metadata:
  name: enforce-readiness-liveness
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptNamespaces:
      - kube-system
      - gatekeeper-system
      - istio-system
