apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSeccomp
metadata:
  name: require-seccomp-profile
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles:
      - runtime/default
    exemptNamespaces: ["istio-system", "kube-system", "gatekeeper-system"]