apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostPaths
metadata:
  name: deny-hostpath
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths: []
    exemptNamespaces: ["istio-system", "kube-system", "gatekeeper-system"]