apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictServiceExternal
metadata:
  name: deny-nodeports
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    types:
      - NodePort
    exemptNamespaces: ["istio-system", "kube-system", "gatekeeper-system"]