apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: "1.26.2"
    helm:
      parameters:
      - name: cni.chained
        value: "true"
      - name: cni.excludeNamespaces[0]
        value: kube-system
      - name: cni.excludeNamespaces[1]
        value: istio-system
      # Uncomment and adjust these if your cluster uses non-standard paths
      # - name: cni.cniBinDir
      #   value: /opt/cni/bin
      # - name: cni.cniConfDir
      #   value: /etc/cni/net.d
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: DaemonSet
    name: istio-cni-node
    jsonPointers:
    - /status
    - /metadata/generation
    - /metadata/resourceVersion
    - /spec/template/metadata/annotations
    - /spec/template/spec/containers/0/env
  - group: apps
    kind: DaemonSet
    name: istio-cni-node
    jqPathExpressions:
    - '.status'
    - '.spec.template.spec.containers[]?.env[]? | select(.name == "NODE_NAME")'
    - '.spec.template.spec.initContainers[]?.env[]? | select(.name == "NODE_NAME")'
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istio-cni
    jsonPointers:
    - /metadata/resourceVersion
    - /metadata/generation
    - /rules
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: istio-cni-repair-role
    jsonPointers:
    - /metadata/resourceVersion
    - /metadata/generation
    - /rules
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: istio-cni
    jsonPointers:
    - /metadata/resourceVersion
    - /metadata/generation