# istio-config/applications/02-istio-control-plane.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.26.2"
    helm:
      parameters:
      - name: pilot.cni.enabled
        value: "true"  # This is crucial - tells istiod not to inject init containers
      - name: pilot.cni.provider
        value: "istio-cni"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionWebhook
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[0].clientConfig.caBundle'
    - '.webhooks[].clientConfig.caBundle'
    - '.metadata.resourceVersion'
    - '.metadata.generation'
