apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psa-secure-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/secure-service-mesh.git
    path: apps/psa
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
