apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: "1.26.2"
    helm:
      parameters:
      - name: cni.chained
        value: "true"
      - name: cni.excludeNamespaces[0]
        value: kube-system
      - name: cni.excludeNamespaces[1]
        value: istio-system
      - name: global.istio_cni.enabled
        value: "true"
      # Uncomment and adjust these if your cluster uses non-standard paths
      # - name: cni.cniBinDir
      #   value: /opt/cni/bin
      # - name: cni.cniConfDir
      #   value: /etc/cni/net.d
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Changed: Don't override runtime adaptations
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true  # Added: Only apply what's actually different
    retry:  # Added: Retry configuration for transient issues
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
  ignoreDifferences:
    # ValidatingWebhookConfiguration differences (existing)
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
        - '.webhooks[]?.failurePolicy'
        - '.webhooks[]?.namespaceSelector'
    # DaemonSet differences (enhanced for CNI-specific issues)
    - group: apps
      kind: DaemonSet
      name: istio-cni-node
      namespace: istio-system
      jsonPointers:
        - /spec/template/spec/containers/0/env
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/nodeSelector
        - /spec/template/spec/tolerations
        - /spec/template/spec/volumes
        - /spec/template/spec/containers/0/volumeMounts
        - /spec/updateStrategy
        - /status
    - group: apps
      kind: DaemonSet
      name: istio-cni-node
      namespace: istio-system
      jqPathExpressions:
        - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
        - .spec.template.metadata.annotations."checksum/config"
        # Added: CNI-specific environment variables that auto-detect
        - '.spec.template.spec.containers[0].env[] | select(.name | test("CNI_NET_DIR|CNI_CONF_NAME|CNI_BIN_DIR"))'
        # Added: Volume mounts that vary by node/distribution
        - '.spec.template.spec.volumes[] | select(.name | test("cni-bin-dir|cni-net-dir|cni-conf-dir"))'
        - '.spec.template.spec.containers[0].volumeMounts[] | select(.name | test("cni-bin-dir|cni-net-dir|cni-conf-dir"))'